CREATE TABLE PERSONA (
    DNI VARCHAR2(9),
    NOM VARCHAR2(50),
    LLINATGES VARCHAR2(50),
    ADRECA VARCHAR2(50),
    CODI_POSTAL NUMBER,
    TELEFON NUMBER,
    PRIMARY KEY (DNI)
)
CREATE TABLE VEHICLE (
    MATRICULA VARCHAR2(7),
    MARCA VARCHAR2(50),
    MODEL VARCHAR2(50),
    DNI_PERSONA VARCHAR2(50),
    PRIMARY KEY (MATRICULA),
    FOREIGN KEY (DNI_PERSONA) REFERENCES PERSONA (DNI)
)
CREATE TABLE MULTA (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    DATA DATE,
    HORA DATE,
    LLOC VARCHAR2(50),
    IMPORT NUMBER,
    MATRICULA_VEHICLE VARCHAR2(7),
    PRIMARY KEY (CODI),
    FOREIGN KEY (MATRICULA_VEHICLE) REFERENCES VEHICLE(MATRICULA)
)
CREATE TABLE ACCIDENT (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    DATA DATE,
    LLOC VARCHAR2(50),
    HORA DATE ,
    PRIMARY KEY (CODI)
)
CREATE TABLE ACCIDENT_VEHICLE (
    MATRICULA_VEHICLE VARCHAR2(7),
    CODI_ACCIDENT NUMBER,
    INFORME_PARTICIPACIO VARCHAR2(50),
    PRIMARY KEY (MATRICULA_VEHICLE),
    PRIMARY KEY (CODI_ACCIDENT),
    FOREIGN KEY (MATRICULA_VEHICLE) REFERENCES VEHICLE(MATRICULA),
    FOREIGN KEY (CODI_ACCIDENT) REFERENCES ACCIDENT(CODI)
)

