CREATE TABLE ENTRENADOR (
    DNI VARCHAR2(9),
    MEDALLES NUMBER,
    PRIMARY KEY (DNI)
)

CREATE TABLE CRIATURA (
    CODI NUMBER PRIMARY KEY, 
    NOM_PROPI VARCHAR2(50),
    NIVELL NUMBER ,
    DNI_ENTRENADOR VARCHAR2(9),
    FOREIGN KEY (DNI_ENTRENADOR) REFERENCES ENTRENADOR(DNI)
)

CREATE TABLE TIPUS (
    NOM VARCHAR2(50) PRIMARY KEY,
    NOM_TIPUS_GUANYA VARCHAR2(50),
    FOREIGN KEY (NOM_TIPUS_GUANYA) REFERENCES TIPUS(NOM)
)

CREATE TABLE ESPECIE (
    NOM VARCHAR2(50) PRIMARY KEY,
    NOM_TIPUS VARCHAR2(50),
    FOREIGN KEY (NOM_TIPUS) REFERENCES TIPUS(NOM)
)

CREATE TABLE INDRET (
    CODI VARCHAR2(50) PRIMARY KEY,
    NOM VARCHAR2(50),
    NOM_TIPUS_DE_BIOMA VARCHAR2(50),
    FOREIGN KEY (NOM_TIPUS_DE_BIOMA) REFERENCES BIOMA(NOM)
)

CREATE TABLE ESPECIE_INDRET (
    NOM_ESPECIE VARCHAR2(50),
    CODI_INDRET NUMBER,
    NV_MIN NUMBER,
    NV_MAX NUMBER,
    PRIMARY KEY (NOM_ESPECIE,CODI_INDRET),
    FOREIGN KEY (NOM_ESPECIE) REFERENCES ESPECIE(NOM),
    FOREIGN KEY (CODI_INDRET) REFERENCES INDRET(CODI)

)