CREATE TABLE HABILIDAD (
    ID INT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion TEXT
);

CREATE TABLE USUARIO (
    DNI VARCHAR(20) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Telefono VARCHAR(15),
    Email VARCHAR(100),
    NomUsuario VARCHAR(50)
);

CREATE TABLE INTERCAMBIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FechaInicio DATE NOT NULL,
    FechaFinal DATE NOT NULL
);

CREATE TABLE SESION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Fecha DATE NOT NULL,
    Duracion INT, -- Duración en minutos
    Descripcion TEXT,
    ID_Intercambio INT,
    FOREIGN KEY (ID_Intercambio) REFERENCES INTERCAMBIO(ID)
);

CREATE TABLE HABILIDAD_USUARIO (
    ID_Habilidad INT,
    DNI_Usuario VARCHAR(20),
    PRIMARY KEY (ID_Habilidad, DNI_Usuario),
    FOREIGN KEY (ID_Habilidad) REFERENCES HABILIDAD(ID),
    FOREIGN KEY (DNI_Usuario) REFERENCES USUARIO(DNI)
);

CREATE TABLE PARTICIPACION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_Habilidad INT,
    DNI_Usuario VARCHAR(20),
    ID_Intercambio INT,
    FOREIGN KEY (ID_Habilidad) REFERENCES HABILIDAD(ID),
    FOREIGN KEY (DNI_Usuario) REFERENCES USUARIO(DNI),
    FOREIGN KEY (ID_Intercambio) REFERENCES INTERCAMBIO(ID)
);
