CREATE TABLE HABILIDAD (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion CLOB
);

CREATE TABLE USUARIO (
    DNI VARCHAR2(20) PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Telefono VARCHAR2(15),
    Email VARCHAR2(100),
    NomUsuario VARCHAR2(50)
);

CREATE TABLE INTERCAMBIO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FechaInicio DATE NOT NULL,
    FechaFinal DATE NOT NULL
);

CREATE TABLE SESION (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Fecha DATE NOT NULL,
    Duracion INT,
    Descripcion CLOB,
    ID_Intercambio INT,
    FOREIGN KEY (ID_Intercambio) REFERENCES INTERCAMBIO(ID)
);

CREATE TABLE HABILIDAD_USUARIO (
    ID_Habilidad INT,
    DNI_Usuario VARCHAR2(20),
    PRIMARY KEY (ID_Habilidad, DNI_Usuario),
    FOREIGN KEY (ID_Habilidad) REFERENCES HABILIDAD(ID),
    FOREIGN KEY (DNI_Usuario) REFERENCES USUARIO(DNI)
);

CREATE TABLE PARTICIPACION (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_Habilidad INT,
    DNI_Usuario VARCHAR2(20),
    ID_Intercambio INT,
    FOREIGN KEY (ID_Habilidad) REFERENCES HABILIDAD(ID),
    FOREIGN KEY (DNI_Usuario) REFERENCES USUARIO(DNI),
    FOREIGN KEY (ID_Intercambio) REFERENCES INTERCAMBIO(ID)
);